// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Ticket
export const SUBMIT_TICKET_REQUEST = 'SUBMIT_TICKET_REQUEST';
export const SUBMIT_TICKET_SUCCESS = 'SUBMIT_TICKET_SUCCESS';
export const SUBMIT_TICKET_FAILURE = 'SUBMIT_TICKET_FAILURE';
